### ISSUE TITLE
Tags should link to the search by tags page

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/tdsb-blog#8]

**Comment by ianfader** [comment]
Tags in the 3 most recent boxes are not linking.

![screen shot 2016-08-29 at 10 00 20 am](https://cloud.githubusercontent.com/assets/8989188/18053878/8b167596-6dcf-11e6-88c6-b06ac2596533.png)

**Comment by hemantcci** [comment]
Whole block is link. Link inside link messing the html structure
